version: '3'

services:
  api:
    container_name: api
    build: .
    restart: always
    volumes:
      - .:/app
      - ../storage:/storage
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: db
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
